title = 'Chirpy'
enableGitInfo = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[pagination]
  pagerSize = 5

[params]
  theme_version = "1.0.0"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"

[module]
[[module.imports]]
  path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[module.imports]]
  path = "github.com/geekifan/chirpy-static-assets"

[[module.imports.mounts]]
  source = "."
  target = "static/lib"

